#!/bin/bash
#
# statusdata.bash
#
# v0.0.1 - 2024-01-11 - nelbren@npr3s.com
#

STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_DEPENDENT=4
STATE_INFO=5
INVERT=1
# From: statusdata.h
SERVICE_PENDING=1
SERVICE_OK=2
SERVICE_WARNING=4
SERVICE_UNKNOWN=8
SERVICE_CRITICAL=16
HOST_PENDING=1
SD_HOST_UP=2
SD_HOST_DOWN=4
SD_HOST_UNREACHABLE=8
CUSTOM_INFO=109
